### ISSUE TITLE
`Index File` Bug

### ISSUE THREAD

**Issue by ahmedHisham2846** [hassanSitblocks/html-first#1]
## Fix The Following 
- Fix indentation.
- Fix **H2O** to be H<sub>2</sub>O

**Comment by hassanSitblocks** [comment]
@ahmedHisham2846 
All of your requests has been edited

**Comment by ahmedHisham2846** [comment]
> @ahmedHisham2846 All of your requests has been edited

Thank you @hassanSitblocks
